apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: hello-world-rest-api
  name: hello-world-rest-api
  namespace: default
spec:
  replicas: 2
  minReadySeconds: 45  #It was added later to define minimum time is required to up the pod to avoid the failure requests
  selector:
    matchLabels:
      app: hello-world-rest-api
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: hello-world-rest-api
    spec:
      containers:
      - image: 114997/hello-world-rest-api:0.0.6-SNAPSHOT
        imagePullPolicy: IfNotPresent
        name: hello-world-rest-api
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app:  hello-world-rest-api
  name:  hello-world-rest-api
  namespace: default
spec:
  ports:
    - nodePort: 30152
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app:  hello-world-rest-api
  sessionAffinity: None
  type: LoadBalancer
