apiVersion: v1
kind: Service
metadata:
  creationTimestamp: 2020-02-13T18:49:02Z
  labels:
    app: hello-world
  name: hello-world
  namespace: default
  resourceVersion: "2870196"
  selfLink: /api/v1/namespaces/default/services/hello-world
  uid: 80ec3c03-4e91-11ea-b0ea-42010a8001d6
spec:
  clusterIP: 10.0.2.231
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30152
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: hello-world
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 35.223.6.207
